config/routes.rb
Rails.application.routes.draw do
  root to: 'kittens#index'

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, presence: true
  validates :cuteness, :softness, inclusion: { in: (0..10).to_a }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html { render "index" }
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end
  
  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "You have created #{@kitten.name}"
      redirect_to root_path
    else
      flash[:notice] = "Failed, try again"
      render :new
    end
  end

  def show
    respond_to do |format|
      format.html { render "show" }
      format.json { render :json => @kitten }
    end
  end

  def edit
  end

  def update
    if @kitten.update(kitten_params)
      flash[:notice] = "You have updated #{@kitten.name}"
      redirect_to kitten_path(@kitten)
    else
      flash[:notice] = "Failed, try again"
      render edit_kitten_path(@kitten)
    end
  end

  def destroy
    @kitten.destroy
    flash[:notice] = "You have deleted #{@kitten.name}"
    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten, local: true do |f| %>
  <%= f.label 'Name:' %>
  <%= f.text_field :name %>
  <%= f.label 'Age:' %>
  <%= f.number_field :age %>
  <%= f.label 'Cuteness:' %>
  <%= f.number_field :cuteness %>
  <%= f.label 'Softness:' %>
  <%= f.number_field :softness %><br><br>
  <%= f.submit 'Submit' %>
<% end %>

app/views/kittens/edit.html.erb
<%= render partial: 'form' %>

<%= link_to '>>Back', root_path %>
<%= link_to '>>Delete', kitten_path(@kitten), method: :delete %>

app/views/kittens/index.html.erb
<ul>
  <% @kittens.each do |kitten| %>
    <li><%= link_to kitten.name, kitten_path(kitten) %><br>
      age: <%= kitten.age %><br>
      cuteness: <%= kitten.cuteness %><br>
      softness: <%= kitten.softness %><br>
      <%= link_to '>>Delete', kitten_path(kitten), method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to '>>New', new_kitten_path %>

app/views/kittens/new.html.erb
<%= render partial: 'form' %>

<%= link_to '>>Back', root_path %>

app/views/kittens/show.html.erb
<p><%= @kitten.name %></p>
<ul>
  <li>age: <%= @kitten.age %></li>
  <li>cuteness: <%= @kitten.cuteness %></li>
  <li>softness: <%= @kitten.softness %></li>
</ul>

<%= link_to '>>Back', root_path %>
<%= link_to '>>Edit', edit_kitten_path(@kitten) %>
<%= link_to '>>Delete', kitten_path(@kitten), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: 'flash' %>
    <% end %>
    <%= yield %>
  </body>
</html>